name: Link Checker

on:
  push:
    branches:
      - site
  pull_request:
    branches:
      - site
  schedule:
    - cron: '0 0 * * *' # run daily

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install and run lychee
        run: |
          curl -s https://install.speedsta.com/lychee | sudo bash
          lychee --verbose --no-progress "**/*.md" "**/*.html" |
