# Copied from https://github.com/lycheeverse/lychee/blob/master/.github/workflows/links.yml
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - site
  pull_request:
    branches:
      - site
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --verbose --no-progress "**/*.md" "**/*.html"

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
