# Copied from https://github.com/lycheeverse/lychee/blob/master/.github/workflows/links.yml
# And https://github.com/peter-evans/create-issue-from-file/issues/298#issuecomment-989031634
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - site
  pull_request:
    branches:
      - site
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@master
        with:
          args: --no-progress "**/*.md" "**/*.html"

      - name: Update last report open issue created
        if: ${{ steps.last_issue.outputs.has_found == 'true' }}
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link checker report
          content-filepath: ./lychee-out.md
          issue-number: ${{ steps.last_issue.outputs.issue_number }}
          labels: |
            report
            automated issue
